### ISSUE TITLE
Error while following installation script: Variable SECONDO_PLATFORM not defined

### ISSUE THREAD

**Issue by sebastian-rombach** [secondo-database/secondo#18]
**Environment**

Secondo version: 4.3.0
System: Ubuntu 20.04.3 LTS -64bit
Memory: 7GB
The system runs on Hyper-V.

**What did I do**
Followed the instructions as laid out in [Installation on Ubuntu 20.04](https://secondo-database.github.io/).
After step 6 - extracting, I moved the folder "secondo" from ~/secondo-RC_430-LAT1 to ~. Navigating there in a terminal session and calling make lead to 

> me@myMachine:~/secondo$ make
> makefile.env:35: *** Variable SECONDO_PLATFORM not defined. Set it to linux, linux64, android, win32 or mac_osx!.  Stop.

During the installation I saw no error messages or warning. The system is set up from scratch.

**What I tried**
- Read the instructionhs repeatedly and carefully.
- I found no answer searching in the wiki "Known problems and solutions"
- Tried to read the makefile. This is basically the first line that is executed.
- Found no comments in the makefile.
- Tried "make -p linux64". Got the same error and a long message starting with 

> \# GNU Make 4.2.1
> \# Built for x86_64-pc-linux-gnu
> \# Copyright (C) 1988-2016 Free Software Foundation, Inc.
> \# License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> \# This is free software: you are free to change and redistribute it.
> \# There is NO WARRANTY, to the extent permitted by law.
> 
> \# Make data base, printed on Sun Sep  5 15:09:34 2021
> 
> \# Variables
> 
> \# environment
> GNUMAKEFLAGS := 
> \# automatic
> <D = $(patsubst %/,%,$(dir $<))
> ....

What do I have to do to install secondo?

**Comment by jnidzwetzki** [comment]
Hello @sebastian-rombach,

Thanks for your bug report. It seems that the `SECONDO_PLATFORM` environment variable is not set on your system. This should be done by your `~/.secondorc`. Could you try to re-read the file by typing `source ~/.secondorc` and try to rebuild SECONDO afterward?

Best Regards
  Jan

**Comment by sebastian-rombach** [comment]
Thank you very much @jnidzwetzki.

Seems I didn't save after step 6. I realized this only after rebooting the system to apply your answer. 
Probably messed up the terminals.

Best regards
Sebastian Rombach
