### ISSUE TITLE
Generating a new relation for symbolic trajectories

### ISSUE THREAD

**Issue by ffeller** [secondo-database/secondo#22]
Hello all,
I'm a bit confused about generating Symbolic Trajectories from imported csv files.
Example:
#Query 1 generating trajectories from a csv imported file
let CheckinSymTraj =
  CheckinData feed 
  extend[CMonth: substr(.CheckinDate, 5, 7) switch["Jan",1;"Feb",2;"Mar",3;"Apr",4;"May",5;"Jun",6;"Jul",7;"Aug";8,"Sep",9;"Oct",10;"Nov",11;"Dec",12;0],
    CDay: str2int(substr(.CheckinDate, 9, 10)),
    CYear: str2int(substr(.CheckinDate, 27, 30)),
    CHour: str2int(substr(.CheckinDate, 12, 13)),
    CMinute: str2int(substr(.CheckinDate, 15, 16)),
    CSecond: str2int(substr(.CheckinDate, 18, 19)),
    CSecond1: str2int(substr(.CheckinDate, 18, 19)) + 1,
    CMillis: str2int(substr(.CheckinDate, 22, 25))]
  extend[CTruncDate: thedate(.CDay, .CMonth, .CYear),
    CInstant: theInstant(.CYear, .CMonth, .CDay, .CHour, .CMinute, .CSecond, .CMillis),
    CInstant1: theInstant(.CYear, .CMonth, .CDay, .CHour, .CMinute, .CSecond1, .CMillis)]
  extend[CLabel: the_unit(tolabel(.VenueId), .CInstant, .CInstant1, TRUE, FALSE)]
  groupby[UserId, CTruncDate; Checkins: group feed makemvalue[CLabel], Cont: group count]
  project[UserId, CTruncDate, Checkins, Cont]  
consume;

#Query 2 generating trajectories from a csv imported file, filtering first for UserId "76"
let CheckinSymTraj2 =
  CheckinData_UserId_btree CheckinData exactmatch["76"] feed 
  extend[CMonth: substr(.CheckinDate, 5, 7) switch["Jan",1;"Feb",2;"Mar",3;"Apr",4;"May",5;"Jun",6;"Jul",7;"Aug";8,"Sep",9;"Oct",10;"Nov",11;"Dec",12;0],
    CDay: str2int(substr(.CheckinDate, 9, 10)),
    CYear: str2int(substr(.CheckinDate, 27, 30)),
    CHour: str2int(substr(.CheckinDate, 12, 13)),
    CMinute: str2int(substr(.CheckinDate, 15, 16)),
    CSecond: str2int(substr(.CheckinDate, 18, 19)),
    CSecond1: str2int(substr(.CheckinDate, 18, 19)) + 1,
    CMillis: str2int(substr(.CheckinDate, 22, 25))]
  extend[CTruncDate: thedate(.CDay, .CMonth, .CYear),
    CInstant: theInstant(.CYear, .CMonth, .CDay, .CHour, .CMinute, .CSecond, .CMillis),
    CInstant1: theInstant(.CYear, .CMonth, .CDay, .CHour, .CMinute, .CSecond1, .CMillis)]
  extend[CLabel: the_unit(tolabel(.VenueId), .CInstant, .CInstant1, TRUE, FALSE)]
  groupby[UserId, CTruncDate; Checkins: group feed makemvalue[CLabel], Cont: group count]
  project[UserId, CTruncDate, Checkins, Cont]  
consume;

But when querying the first relation for user "76" the result doesn't match with the second one.
#Query1
query CheckinSymTraj_UserId_btree CheckinSymTraj exactmatch["76"] project [UserId, CTruncDate, Cont] sortby[Cont, CTruncDate] consume;
#Query2
query CheckinSymTraj2 feed project [UserId, CTruncDate, Cont] sortby[Cont, CTruncDate] consume;

It seems that in CheckinSymTraj relation it hasn't grouped the results whilst it has in the CheckinSymTraj2 relation.

Am I missing something at the first query?

Regards, 
Flaris.

**Comment by ralfgueting** [comment]
groupby requires a stream sorted in the order of grouping attributes. So normally you need to put a sort operator in front, here

sortby[UserId, CTruncDate]

**Comment by ffeller** [comment]
Hello Professor Ralf,
Indeed, I haven't noticed this detail at the Secondo's official documentation.
Thank you very much!
Regards,
Flaris.

**Comment by ffeller** [comment]
Hello Professor Ralf,
After I rerun the load of the two relations I've noticed there are differences when displaying "Checkins" attribute of type mlabel from each one of them:
#Query 1:
SecondoPLTTY => query CheckinSymTraj2 feed filter[.Cont = 42] project[UserId, CTruncDate, Cont, Checkins] consume;

(query 
    (consume 
        (project 
            (filter 
                (feed CheckinSymTraj2) 
                (fun 
                    (streamelem_1 STREAMELEM) 
                    (= 
                        (attr streamelem_1 Cont) 
                        42))) 
            (UserId CTruncDate Cont Checkins))))
noMemoryOperators = 0
perOperator = 0
Total runtime ...   Times (elapsed / cpu): 0.038369sec / 0.02sec = 1.91845

    UserId : 76
CTruncDate : 05.05.2012
      Cont : 42
  Checkins : Generic display function used!
Type : mlabel
Value: 
(
    (
        ("2012-05-05-05:54:54" "2012-05-05-05:54:55" TRUE FALSE) 
        '4adcdac6f964a5202d5321e3') 
    (
        ("2012-05-05-05:58:03" "2012-05-05-05:58:04" TRUE FALSE) 
        '4adcdac6f964a5200d5321e3') 
    (
        ("2012-05-05-05:59:06" "2012-05-05-05:59:07" TRUE FALSE) 
        '4e8bab8fb803540e781e7d03') 
    (
        ("2012-05-05-05:59:22" "2012-05-05-05:59:23" TRUE FALSE) 
        '4adcdac6f964a520355321e3') 
    (
        ("2012-05-05-05:59:38" "2012-05-05-05:59:39" TRUE FALSE) 
        '4f09f2c9e4b07c8f8daa4caa') 
    (
        ("2012-05-05-06:00:28" "2012-05-05-06:00:29" TRUE FALSE) 
        '4c41fd5c520fa593517ccaac') 
    (
        ("2012-05-05-06:00:47" "2012-05-05-06:00:48" TRUE FALSE) 
        '4adcdac6f964a520335321e3') 
    (
        ("2012-05-05-06:01:03" "2012-05-05-06:01:04" TRUE FALSE) 
        '4e92cba98231bf0d178c6e8d') 
    (
        ("2012-05-05-06:32:26" "2012-05-05-06:32:27" TRUE FALSE) 
        '4dfaf868d22d56d1ebadb974') 
    (
        ("2012-05-05-06:32:40" "2012-05-05-06:32:41" TRUE FALSE) 
        '4da066923edff04d88a13f99') 
    (
        ("2012-05-05-06:33:28" "2012-05-05-06:33:29" TRUE FALSE) 
        '4db347c95da3a76f44264279') 
    (
        ("2012-05-05-06:52:10" "2012-05-05-06:52:11" TRUE FALSE) 
        '4bd5869b7b1876b0bed18a86') 
    (
        ("2012-05-05-07:19:09" "2012-05-05-07:19:10" TRUE FALSE) 
        '4b8e9668f964a5206a2a33e3') 
    (
        ("2012-05-05-07:19:31" "2012-05-05-07:19:32" TRUE FALSE) 
        '4e8bab8fb803540e781e7d03') 
    (
        ("2012-05-05-07:19:51" "2012-05-05-07:19:52" TRUE FALSE) 
        '4c1df65ffcf8c9b6fb8bac0b') 
    (
        ("2012-05-05-07:20:08" "2012-05-05-07:20:09" TRUE FALSE) 
        '4df393c6b61cbd3ec01ba372') 
    (
        ("2012-05-05-07:27:02" "2012-05-05-07:27:03" TRUE FALSE) 
        '4e8bab8fb803540e781e7d03') 
    (
        ("2012-05-05-07:28:05" "2012-05-05-07:28:06" TRUE FALSE) 
        '4d977dd9daec224b920d323e') 
    (
        ("2012-05-05-07:28:32" "2012-05-05-07:28:33" TRUE FALSE) 
        '4be44735cf200f4719b7113c') 
    (
        ("2012-05-05-11:05:16" "2012-05-05-11:05:17" TRUE FALSE) 
        '4bd6f610637ba593c5f7f870') 
    (
        ("2012-05-05-11:05:34" "2012-05-05-11:05:35" TRUE FALSE) 
        '4adcdac6f964a520105321e3') 
    (
        ("2012-05-05-11:05:52" "2012-05-05-11:05:53" TRUE FALSE) 
        '4adcdac8f964a520c85321e3') 
    (
        ("2012-05-05-11:06:07" "2012-05-05-11:06:08" TRUE FALSE) 
        '4dc269aad1643ed27a4e08c4') 
    (
        ("2012-05-05-11:06:28" "2012-05-05-11:06:29" TRUE FALSE) 
        '4c121b1377cea5933863cc60') 
    (
        ("2012-05-05-11:06:44" "2012-05-05-11:06:45" TRUE FALSE) 
        '4b818c55f964a5202fae30e3') 
    (
        ("2012-05-05-15:01:43" "2012-05-05-15:01:44" TRUE FALSE) 
        '4ea9edb56c250fcc73f883ef') 
    (
        ("2012-05-05-15:01:57" "2012-05-05-15:01:58" TRUE FALSE) 
        '4adcdac6f964a5202b5321e3') 
    (
        ("2012-05-05-15:02:34" "2012-05-05-15:02:35" TRUE FALSE) 
        '4adcdac6f964a5201e5321e3') 
    (
        ("2012-05-05-15:02:59" "2012-05-05-15:03" TRUE FALSE) 
        '4bee65ef35dc0f470bcc3f5b') 
    (
        ("2012-05-05-15:03:44" "2012-05-05-15:03:45" TRUE FALSE) 
        '4e32a32988776e6696f9d5c4') 
    (
        ("2012-05-05-15:05:35" "2012-05-05-15:05:36" TRUE FALSE) 
        '4f22ad65e4b067a324f95850') 
    (
        ("2012-05-05-15:07:19" "2012-05-05-15:07:20" TRUE FALSE) 
        '4adcdac6f964a520355321e3') 
    (
        ("2012-05-05-15:55:47" "2012-05-05-15:55:48" TRUE FALSE) 
        '4dfaf868d22d56d1ebadb974') 
    (
        ("2012-05-05-15:56:13" "2012-05-05-15:56:14" TRUE FALSE) 
        '4eba5754c2eea05f84e18cd8') 
    (
        ("2012-05-05-16:08:31" "2012-05-05-16:08:32" TRUE FALSE) 
        '4adcdac6f964a520175321e3') 
    (
        ("2012-05-05-16:08:45" "2012-05-05-16:08:46" TRUE FALSE) 
        '4c1df65ffcf8c9b6fb8bac0b') 
    (
        ("2012-05-05-16:15:17" "2012-05-05-16:15:18" TRUE FALSE) 
        '4adcdac6f964a520335321e3') 
    (
        ("2012-05-05-16:32:52" "2012-05-05-16:32:53" TRUE FALSE) 
        '4adcdac7f964a5208b5321e3') 
    (
        ("2012-05-05-16:36" "2012-05-05-16:36:01" TRUE FALSE) 
        '4f059eded3e321b78f826f34') 
    (
        ("2012-05-05-16:36:32" "2012-05-05-16:36:33" TRUE FALSE) 
        '4db0f7654b22ba776d7a52b4') 
    (
        ("2012-05-05-16:44:15" "2012-05-05-16:44:16" TRUE FALSE) 
        '4dab45cca86e771ea73643d6') 
    (
        ("2012-05-05-16:45:27" "2012-05-05-16:45:28" TRUE FALSE) 
        '4adcdac9f964a520265421e3'))


#Query 2:
SecondoPLTTY => query CheckinSymTraj_UserId_btree CheckinSymTraj exactmatch["76"] filter[.Cont = 42] project[UserId, CTruncDate, Cont, Checkins]  consume;

(query 
    (consume 
        (project 
            (filter 
                (exactmatch CheckinSymTraj_UserId_btree CheckinSymTraj "76") 
                (fun 
                    (streamelem_1 STREAMELEM) 
                    (= 
                        (attr streamelem_1 Cont) 
                        42))) 
            (UserId CTruncDate Cont Checkins))))
noMemoryOperators = 0
perOperator = 0
Total runtime ...   Times (elapsed / cpu): 0.019106sec / 0.01sec = 1.9106

    UserId : 76
CTruncDate : 05.05.2012
      Cont : 42
  Checkins : Generic display function used!
Type : mlabel
Value: 
(
    (
        ("2000-01-03" "2000-01-03" TRUE TRUE) 
'))     'a

In Query1 which uses CheckinSymTraj2 relation, the results are presented successfully but in Query2 which uses CheckinSymTraj relation, it seems that "Checkins" attribute is truncated.
Am I missing anything else at Query2 or at build phase?
Thanks in advance.
Regards,
Flaris.

**Comment by ralfgueting** [comment]
Dear Flaris, it has nothing to do with the query, that is feed filter or exactmatch yield the same tuples.

However, the Checkins attribute is constructed by the makemvalue operation. This operator needs to receive the CLabel units in temporal order to work correctly. I do not see that you sort them in your construction. I am not sure (without checking) whether you can sort the CLabel values directly (i.e., just by the CLabel attribute); otherwise you need to sort the CInstant values before creating the CLabel values.

I admit that this is not mentioned in the Symbolic Trajectories paper; and I am not sure that the SQL construction shown there is correct, because it does not sort by time.

Regards
Ralf

**Comment by ffeller** [comment]
Hello Professor Ralf,
Sure, I should've noticed that there was the need to sort the labels by a time dimension, to successfully put them all together in a mlabel attribute. I've done that sorting the stream including the CInstant attribute along with UserId and CTruncDate ones.
Thanks again.
Regards,
Flaris.

**Comment by ralfgueting** [comment]
Fine. I have checked in the meantime that you can also apply sorting directly to an attribute of type ulabel; it will sort by time.

**Comment by ralfgueting** [comment]
> Dear Flaris, it has nothing to do with the query, that is feed filter or exactmatch yield the same tuples.
> 
> However, the Checkins attribute is constructed by the makemvalue operation. This operator needs to receive the CLabel units in temporal order to work correctly. I do not see that you sort them in your construction. I am not sure (without checking) whether you can sort the CLabel values directly (i.e., just by the CLabel attribute); otherwise you need to sort the CInstant values before creating the CLabel values.
> 
> I admit that this is not mentioned in the Symbolic Trajectories paper; and I am not sure that the SQL construction shown there is correct, because it does not sort by time.
> 
> Regards Ralf

I found that my previous comment was wrong. makemvalue does sort the units it processes by itself. Sorry that I did not check before commenting.
