### ISSUE TITLE
Join method

### ISSUE THREAD

**Issue by ffeller** [secondo-database/secondo#23]
Hello all,
I have two relations: CheckinData with 33263633 rows and POIData with 3680126 rows, which I need join them in a query by VenueId attribute :
   (OBJECT CheckinData 
        () 
        (
            (rel 
                (tuple 
                    (
                        (UserId string) 
                        (VenueId string) 
                        (CheckinDate string) 
                        (TzOffset int)))))) 
 

   (OBJECT POIData 
        () 
        (
            (rel 
                (tuple 
                    (
                        (VenueID string) 
                        (Latitude real) 
                        (Longitude real) 
                        (VenueCategoryName string) 
                        (CountryCode string)))))) 

Which join method would you recommend for better performance in a situation like that?
Thanks in advance,
Flaris.

**Comment by ralfgueting** [comment]
I suggest to use the query optimizer (i.e., SQL).  I guess it would use a kind of hashjoin.

**Comment by ffeller** [comment]
Hello Professor,
I found that a sortmergejoin was the best approach for a join for this case. 
Thank you.
Regards,
Flaris.
