### ISSUE TITLE
ISO C++17 does not allow 'register' storage class specifier [-Wregister]

### ISSUE THREAD

**Issue by fischerjulian** [secondo-database/secondo#4]
The compilation of the current CVS version of Secondo fails with the following error message - even after running `make clean`:

```
NLLex.cpp:812:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register yy_state_type yy_current_state;
        ^~~~~~~~~
NLLex.cpp:813:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *yy_cp, *yy_bp;

[...]
```

**Comment by jnidzwetzki** [comment]
Hi @fischerjulian,

Thanks for the bug report. It seems you are [using an outdated version of Flex](https://github.com/secondo-database/secondo/wiki/Known-Problems-and-Solutions#compile-error-register-storage-class-specifier-is-deprecated-and-incompatible-with-c17). Older flex versions don't generate C++17 compatible code. 

Please check your Flex installation and upgrade Flex to at least version 2.6.4. Ubuntu >= 18.04 ships with proper versions. If you are using OS X, you find the upgrade instructions [here](http://dna.fernuni-hagen.de/Secondo.html/files/Installation/Mac/Catalina-Installation-Guide.html).

If you still have problems, please do not hesitate to contact us.

Best Regards
   Jan

**Comment by fischerjulian** [comment]
Hi @jnidzwetzki, thank you very much for your help. It worked 👍
